Repository jbx-protocol/juice-interface, pull requests merged in 2022-07, with the labels that each got.

#1275 Use the latest configured FC in the Upcoming tab
  src/components/shared/Badge.tsx
  src/components/shared/Project/FundingCycleDetailsCard.tsx
  src/components/v2/V2Project/V2FundingCycleSection/UpcomingFundingCycle.tsx
  src/constants/v1/ballotStrategies/index.ts
  src/constants/v2/ballotStrategies/getBallotStrategiesByAddress.ts
  src/hooks/v2/contractReader/ProjectLatestConfiguredFundingCycle.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/models/v2/fundingCycle.ts
  src/styles/antd-overrides/tooltip.scss
Labels: bug, UX, V2, severity::1

#1317 Fix project owner context in V1
  src/components/v1/V1Dashboard.tsx
  src/hooks/v1/contractReader/OwnerOfProject.ts
Labels: bug, severity::1

#1336 Add project config option for `allowSetTerminals`
  src/components/v2/V2Project/V2FundingCycleSection/FundingCycleDetails.tsx
  src/components/v2/V2Project/V2ProjectReconfigureModal/ReconfigurePreview.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/pages/create/forms/RulesForm/index.tsx
  src/pages/create/tabs/ReviewDeployTab/FundingAttributes.tsx
  src/pages/create/tabs/ReviewDeployTab/FundingSummarySection.tsx
  src/redux/slices/editingV2Project.ts
  src/utils/v2/__tests__/fundingCycle.test.ts
  src/utils/v2/fundingCycle.ts
Labels: enhancement, V2

#1338 Make upload button transparent
  src/styles/antd-overrides/button.scss
  src/styles/antd-overrides/input.scss
Labels: bug, severity::3

#1339 Fix edit payouts amount precision
  src/components/v1/shared/ProjectPayMods/ProjectModInput.tsx
  src/components/v2/shared/DistributionSplitsSection/DistributionSplitCard.tsx
Labels: bug, severity::3

#1340 Bump @jbx-protocol/contracts-v1 to v2.0.0
  package.json
  yarn.lock
Labels: housekeeping

#1342 Distribute buttons improvements
  src/components/FormattedAddress.tsx
  src/components/Project/SpendingStats.tsx
  src/components/v1/shared/FundingCycle/Spending.tsx
  src/components/v2/V2Project/V2FundingCycleSection/PayoutSplitsCard.tsx
  src/components/v2/V2Project/V2FundingCycleSection/ReservedTokensSplitsCard.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: enhancement

#1359 Only add memo metadata with images or stickers
  src/components/v2/V2Project/V2PayButton/V2ConfirmPayModal/index.tsx
Labels: bug, severity::3

#1426 Refactor tools drawer
  src/components/Project/ProjectToolsDrawer/ProjectToolsDrawer.tsx
  src/components/v1/V1Project/V1ProjectHeaderActions.tsx
  src/components/v1/V1Project/V1ProjectToolsDrawer.tsx
  src/components/v2/V2Project/V2ProjectHeaderActions.tsx
  src/components/v2/V2Project/V2ProjectToolsDrawer/V1TokenMigrationSetupSection/V1TokenMigrationSetupModal/AddTerminalSection.tsx
  src/components/v2/V2Project/V2ProjectToolsDrawer/V1TokenMigrationSetupSection/V1TokenMigrationSetupModal/SetV1ProjectSection.tsx
  src/components/v2/V2Project/V2ProjectToolsDrawer/V1TokenMigrationSetupSection/V1TokenMigrationSetupModal/StepSection.tsx
  src/components/v2/V2Project/V2ProjectToolsDrawer/V1TokenMigrationSetupSection/V1TokenMigrationSetupModal/V1TokenMigrationSetupModal.tsx
  src/components/v2/V2Project/V2ProjectToolsDrawer/V1TokenMigrationSetupSection/V1TokenMigrationSetupModal/index.tsx
  src/components/v2/V2Project/V2ProjectToolsDrawer/V1TokenMigrationSetupSection/V1TokenMigrationSetupSection.tsx
  src/components/v2/V2Project/V2ProjectToolsDrawer/V1TokenMigrationSetupSection/index.ts
  src/components/v2/V2Project/V2ProjectToolsDrawer/V2ProjectToolsDrawer.tsx
  src/components/v2/V2Project/V2ProjectToolsDrawer/index.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: bug, housekeeping, severity::3

#1444 Fix FC number not showing
  src/components/Project/BallotStateBadge.tsx
  src/components/Project/FundingCycleDetailsCard.tsx
  src/components/Project/SpendingStats.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: type:bug, severity:3

#1468 Dont default to useDataSourceForPay true
  src/redux/slices/editingV2Project.ts
Labels: type:bug, severity:1

#1475 Enable NFT projects `useDataSourceForPay` and fix OpenSea NFT images
  src/hooks/v2/NftRewards.ts
  src/hooks/v2/contractReader/NftRewardTiersOf.ts
  src/hooks/v2/transactor/LaunchProjectWithNftsTx.ts
  src/models/v2/nftRewardTier.ts
  src/pages/create/tabs/ReviewDeployTab/DeployProjectWithNftsButton.tsx
  src/utils/ipfs.ts
  src/utils/v2/nftRewards.ts
Labels: type:bug, severity:1

#1458 Juiced README
  .github/CODEOWNERS
  CONTRIBUTING.md
  README.md
  doc/architecture/theme.md
  doc/architecture/web3-providers.md
  doc/development.md
  doc/devops.md
  doc/internationalization.md
Labels: type:maintenance, documentation

#1488 Archive some projects
  src/constants/v1/archivedProjects.ts
  src/constants/v1/projectIds.ts
  src/constants/v2/archivedProjects.ts
  src/constants/v2/projectIds.ts
Labels: archive request

#1516 Fix social link styling
  src/components/Project/ProjectHeader/SocialLinks.tsx
  src/constants/v2/archivedProjects.ts
  src/constants/v2/projectIds.ts
Labels: type:bug, archive request, severity:3

#1542 Add hotjar + update privacy policy
  src/components/common/Head/Head.tsx
  src/pages/privacy.page.tsx
Labels: type:maintenance

#1551 Add basic validation to github archive endpoint
  src/pages/api/github/archive-project.page.ts
Labels: type:bug, severity:2

#1463 Validate FC mustStartAtOrAfter + duration
  src/constants/numbers.ts
  src/hooks/v2/transactor/LaunchFundingCyclesTx.ts
  src/hooks/v2/transactor/LaunchProjectTx.ts
  src/hooks/v2/transactor/LaunchProjectWithNftsTx.ts
  src/hooks/v2/transactor/ReconfigureV2FundingCycleTx.ts
  src/pages/create/forms/FundingForm/index.tsx
  src/utils/v2/__tests__/fundingCycle.test.ts
  src/utils/v2/fundingCycle.ts
  src/utils/v2/math.ts
Labels: type:bug, severity:2

#1562 Styling regression fixes
  src/components/Project/ProjectHeader/SocialLinks.tsx
  src/components/inputs/Pay/PayInputGroup.tsx
Labels: type:bug, ux, severity:3, ux:contributor

#1554 Fix a few nav item bugs
  src/components/Navbar/MenuItems.tsx
  src/components/Navbar/Mobile/MobileCollapse.tsx
  src/components/Navbar/Wallet.tsx
Labels: type:bug, severity:2

#1519 Add TransactionModal to V1 Withdraw modal
  src/components/v1/shared/FundingCycle/Spending.tsx
  src/components/v1/shared/FundingCycle/modals/WithdrawModal.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: type:bug, ux, severity:2

#1546 Fix stale token symbol
  src/hooks/NameOfERC20.ts
  src/hooks/SymbolOfERC20.ts
Labels: type:bug, severity:2

#1579 Fix payable address beneficiary bug
  src/components/MinimalCollapse.tsx
  src/components/v2/V2Project/LaunchProjectPayer/AdvancedOptionsCollapse.tsx
  src/components/v2/V2Project/LaunchProjectPayer/LaunchProjectPayerModal.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: type:bug, severity:1

#1580 Fix erc 20 pay v2
  src/components/v2/V2Project/V2PayButton/V2ConfirmPayModal/index.tsx
  src/components/v2/V2Project/V2PayButton/V2PayForm/V2PayForm.tsx
  src/hooks/v2/transactor/PayETHPaymentTerminal.ts
  src/pages/api/ipfs/pin.page.ts
Labels: type:bug, priority:1

#1607 Only show network warning modal wen connected
  src/components/common/CoreAppWrapper/CoreAppWrapper.tsx
Labels: type:bug, priority:2
