Repository jbx-protocol/juice-interface, pull requests merged in 2022-09, with the labels that each got.

#1900 Update favicon and Gnosis Safe manifest
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/manifest.json
  public/mstile-144x144.png
  public/mstile-150x150.png
  public/mstile-310x150.png
  public/mstile-310x310.png
  public/mstile-70x70.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  src/components/common/Head/Head.tsx
Labels: priority:3

#1940 Distribution limit bug fix
  src/components/v1/V1Project/index.tsx
  src/components/v1/V1Project/modals/ReconfigureFCModal.tsx
  src/components/v1/V1Project/modals/V1ConfirmPayOwnerModal.tsx
  src/components/v1/shared/FundingCycle/FundingCycleDetails.tsx
  src/components/v1/shared/FundingCycle/modals/WithdrawModal.tsx
  src/components/v1/shared/PayoutModsList.tsx
  src/components/v1/shared/ProjectPayMods/ProjectModInput.tsx
  src/components/v1/shared/ProjectPayMods/ProjectPayoutModsModal.tsx
  src/locales/messages.pot
  src/pages/create/forms/FundingForm/DistributionSplitsSection/AmountFormItem.tsx
  src/pages/create/forms/FundingForm/DistributionSplitsSection/DistributionSplitModal.tsx
  src/pages/v1/create/ConfirmDeployProject.tsx
  src/utils/math.ts
  src/utils/v1/math.ts
  src/utils/v1/payouts.ts
Labels: type:bug, priority:1

#1958 Use V2ProjectHandle in more places
  src/components/v2/V2Project/ProjectActivity/eventElems/DistributePayoutsElem.tsx
  src/components/v2/shared/SplitItem.tsx
  src/components/v2/shared/V2ProjectHandle.tsx
  src/locales/messages.pot
  src/pages/home/Payments.tsx
Labels: type:bug
