Repository jbx-protocol/juice-interface, pull requests merged in 2022-05, with the labels that each got.

#895 Update review and deploy tab on V2 create
  src/components/Projects/ProjectsFilterAndSort.tsx
  src/components/v2/V2Create/index.tsx
  src/components/v2/V2Create/tabs/ReviewDeployTab/FundingSection.tsx
  src/components/v2/V2Create/tabs/ReviewDeployTab/ProjectDetailsSection.tsx
  src/components/v2/V2Create/tabs/ReviewDeployTab/index.tsx
  src/components/v2/V2Project/V2FundingCycleSection/FundingCycleDetails.tsx
  src/components/v2/V2Project/V2FundingCycleSection/settingExplanations.tsx
  src/components/v2/shared/SplitItem.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/utils/v2/fundingCycle.ts
Labels: V2

#880 Fix form extra
  src/components/shared/ReconfigurationStrategy/ReconfigurationStrategySelector.tsx
  src/components/shared/SwitchHeading.tsx
  src/components/shared/formItems/ProjectBondingCurveRate.tsx
  src/components/shared/formItems/ProjectDiscountRate.tsx
  src/components/shared/formItems/ProjectReserved.tsx
  src/components/v2/V2Create/forms/FundingForm/index.tsx
  src/components/v2/V2Create/forms/TokenForm/index.tsx
  src/components/v2/V2Project/V2FundingCycleSection/settingExplanations.tsx
  src/components/v2/V2Project/V2ProjectReconfigureModal/V2ReconfigureUpcomingMessage.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/styles/antd-overrides/input.scss
Labels: enhancement

#925 Fixed leaked merge conflict <<<HEAD
  src/locales/en/messages.po
Labels: bug

#926 Lint translation files for git merge conflict txt
  scripts/lint-translations.sh
Labels: housekeeping

#952 Route updates for V2
  src/Router.tsx
  src/components/Landing/Footer.tsx
  src/components/Landing/V2Switch.tsx
  src/components/Landing/index.tsx
  src/components/Projects/index.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/utils/featureFlags.ts
Labels: V2

#947 Bump v2-contracts v3.0.1
  package.json
  src/Router.tsx
  src/components/Landing/Footer.tsx
  src/components/Landing/V2Switch.tsx
  src/components/Landing/index.tsx
  src/components/Navbar/constants.ts
  src/components/Projects/index.tsx
  src/components/shared/ManageTokensModal.tsx
  src/components/shared/Project/FundingCycleDetailsCard.tsx
  src/components/shared/currency/ETHAmount.tsx
  src/components/shared/modals/IssueTokenModal.tsx
  src/components/v1/V1Project/modals/ConfirmUnstakeTokensModal.tsx
  src/components/v1/V1Project/modals/PrintPreminedModal.tsx
  src/components/v2/V2Create/forms/FundingForm/index.tsx
  src/components/v2/V2Dashboard/index.tsx
  src/components/v2/V2Project/TreasuryStats/DistributedRatio.tsx
  src/components/v2/V2Project/V2FundingCycleSection/CurrentFundingCycle.tsx
  src/components/v2/V2Project/V2FundingCycleSection/FundingCycleDetails.tsx
  src/components/v2/V2Project/V2FundingCycleSection/FundingCycleHistory.tsx
  src/components/v2/V2Project/V2FundingCycleSection/PayoutSplitsCard.tsx
  src/components/v2/V2Project/V2FundingCycleSection/ReservedTokensSplitsCard.tsx
  src/components/v2/V2Project/V2FundingCycleSection/UpcomingFundingCycle.tsx
  src/components/v2/V2Project/V2ManageTokensSection/V2ClaimTokensModal.tsx
  src/components/v2/V2Project/V2ManageTokensSection/V2MintModal.tsx
  src/components/v2/V2Project/V2ManageTokensSection/V2RedeemModal.tsx
  src/components/v2/V2Project/V2ManageTokensSection/index.tsx
  src/components/v2/V2Project/V2PayButton/V2ConfirmPayModal/index.tsx
  src/components/v2/V2Project/V2PayButton/index.tsx
  src/components/v2/V2Project/index.tsx
  src/components/v2/shared/SplitItem.tsx
  src/constants/v2/ballotStrategies/index.ts
  src/constants/v2/metadataDomain.ts
  src/hooks/v2/contractReader/ProjectCurrentFundingCycle.ts
  src/hooks/v2/contractReader/ProjectDistributionLimit.ts
  src/hooks/v2/contractReader/ProjectMetadataContent.ts
  src/hooks/v2/transactor/DistributePayouts.ts
  src/hooks/v2/transactor/EditV2ProjectDetailsTx.ts
  src/hooks/v2/transactor/LaunchProjectTx.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/models/v2/fundingCycle.ts
  src/redux/slices/editingV2Project.ts
  src/utils/featureFlags.ts
  src/utils/v2/__tests__/fundingCycle.test.ts
  src/utils/v2/fundingCycle.ts
  src/utils/v2/serializers.ts
  yarn.lock
Labels: V2

#949 Close modal on network change
  src/providers/NetworkProvider.tsx
Labels: bug

#982 Enable V2 on mainnet
  src/components/v2/V2Project/index.tsx
  src/utils/featureFlags.ts
Labels: V2

#984 Clean up ENABLE_V2 feature flag
  src/Router.tsx
  src/components/Landing/Footer.tsx
  src/components/Landing/V2Switch.tsx
  src/components/Landing/index.tsx
  src/components/v1/V1Project/index.tsx
  src/components/v2/V2EntryGuard.tsx
  src/components/v2/shared/V2SupportWarning.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/utils/featureFlags.ts
Labels: V2

#1007 Wrap and expand pay button better, v1/v2
  src/components/shared/inputs/Pay/PayInputGroup.tsx
  src/components/v1/V1Project/V1PayButton.tsx
  src/components/v2/V2Project/V2PayButton/index.tsx
Labels: bug, high priority

#975 Above-the-fold copy updates + SEO/ performance improvements
  public/assets/banana-cover.png
  public/assets/blueberry-ol.png
  public/assets/bolt.png
  public/assets/bolt.svg
  public/assets/green_orange.png
  public/assets/juice_logo-od.png
  public/assets/juice_logo-ol.png
  public/assets/orange_lady-od.png
  public/assets/orange_lady-ol.png
  public/assets/pina.png
  public/assets/stoned_banny.png
  public/index.html
  src/Router.tsx
  src/components/Landing/Footer.tsx
  src/components/Landing/TrendingSection.tsx
  src/components/Landing/index.tsx
  src/components/shared/RichImgPreview.tsx
  src/components/v1/V1Dashboard/index.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/styles/index.scss
Labels: enhancement, performance

#1020 Hide volume chart in Create project preview
  src/components/v2/V2Project/index.tsx
Labels: bug

#1025 More pay button fixes
  src/components/shared/inputs/FormattedNumberInput.tsx
  src/components/shared/inputs/Pay/PayInputGroup.tsx
  src/components/v1/V1Project/V1PayButton.tsx
  src/components/v2/V2Project/V2PayButton/index.tsx
Labels: bug, high priority

#1062 Fixes pay disabled
  src/components/Landing/index.tsx
  src/components/Projects/TrendingProjects.tsx
  src/components/shared/CardSection.tsx
  src/components/v1/V1Project/V1PayButton.tsx
  src/components/v2/V2Create/forms/FundingForm/index.tsx
  src/components/v2/V2Project/V2FundingCycleSection/PayoutSplitsCard.tsx
  src/constants/theme/colors/background.ts
  src/styles/antd-overrides/button.scss
  src/styles/index.scss
  src/styles/utilities.scss
Labels: bug

#1063 Fix FC metadata sync on preview
  src/components/v2/V2Project/V2FundingCycleSection/CurrentFundingCycle.tsx
  src/components/v2/V2Project/V2FundingCycleSection/FundingCycleDetails.tsx
  src/components/v2/V2Project/V2FundingCycleSection/FundingCycleHistory.tsx
  src/components/v2/V2Project/V2FundingCycleSection/UpcomingFundingCycle.tsx
Labels: bug, high priority

#1085 Upgrade JB contracts + project relaunch FC UI
  package.json
  src/components/V2BugUpdates/index.tsx
  src/components/shared/Banner.tsx
  src/components/v2/V2Create/tabs/ReviewDeployTab/FundingAttributes.tsx
  src/components/v2/V2Project/V2FundingCycleSection/NoFundingCycle.tsx
  src/components/v2/V2Project/V2FundingCycleSection/index.tsx
  src/components/v2/V2Project/banners/RelaunchFundingCycleBanner/index.tsx
  src/components/v2/V2Project/index.tsx
  src/constants/v2/ballotStrategies/index.ts
  src/hooks/v2/V2ContractLoader.ts
  src/hooks/v2/contractReader/ProjectCurrentFundingCycle.ts
  src/hooks/v2/contractReader/ProjectDistributionLimit.ts
  src/hooks/v2/contractReader/ProjectSplits.ts
  src/hooks/v2/contractReader/ProjectTerminals.ts
  src/hooks/v2/transactor/LaunchFundingCyclesTx.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/models/v2/contracts.ts
  yarn.lock
Labels: critical

#1116 Typo fix
  src/components/v2/V2Create/forms/FundingForm/FundingCycleExplainerCollapse.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: bug
