Repository jbx-protocol/juice-interface, pull requests merged in 2022-03, with the labels that each got.

#626 Add V2 funding cycle metadata decoder
  package.json
  src/components/shared/PayoutModsList.tsx
  src/components/shared/TicketModsList.tsx
  src/components/shared/formItems/ProjectPayoutMods.tsx
  src/components/shared/formItems/ProjectTicketMods.tsx
  src/components/shared/formItems/formHelpers.tsx
  src/components/shared/inputs/BudgetTargetInput.tsx
  src/components/v1/FundingCycle/FundingCycleDetails.tsx
  src/components/v1/FundingCycle/ReservedTokens.tsx
  src/components/v1/FundingCycle/Spending.tsx
  src/components/v1/FundingCycle/modals/WithdrawModal.tsx
  src/components/v1/V1Create/ConfirmDeployProject.tsx
  src/components/v1/V1Create/index.tsx
  src/components/v1/V1Project/modals/ReconfigureFCModal.tsx
  src/components/v2/V2Create/DeployProjectModal/PayoutSplitsList.tsx
  src/components/v2/V2Project/index.tsx
  src/models/v2/fundingCycle.ts
  src/redux/slices/editingProject.ts
  src/redux/slices/editingV2Project.ts
  src/utils/bigNumbers.ts
  src/utils/formatNumber.ts
  src/utils/math.ts
  src/utils/v1/fundingCycle.ts
  src/utils/v1/serializers.ts
  src/utils/v2/__tests__/fundingCycle.test.ts
  src/utils/v2/fundingCycle.ts
  src/utils/v2/serializers.ts
Labels: Juicebox V2

#638 Remove [prefix] from issue template titles
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement.md
Labels: housekeeping

#646 Project creation fixes
  src/components/shared/Paragraph.tsx
  src/components/shared/RichNote.tsx
  src/components/v1/V1Create/index.tsx
  src/redux/slices/editingProject.ts
  src/utils/formatDate.tsx
Labels: bug, bugish

#635 V2 project pay button
  src/components/shared/inputs/Pay/PayInputGroup.tsx
  src/components/shared/inputs/Pay/PayInputSubText.tsx
  src/components/v1/V1Project/V1PayButton.tsx
  src/components/v1/V1Project/modals/PayWarningModal.tsx
  src/components/v1/V1Project/modals/V1ConfirmPayOwnerModal/index.tsx
  src/components/v2/V2Create/DeployProjectModal/PayoutSplitsList.tsx
  src/components/v2/V2Create/index.tsx
  src/components/v2/V2Create/tabs/FundingTab/FundingTabContent.tsx
  src/components/v2/V2Dashboard/index.tsx
  src/components/v2/V2Project/V2ConfirmPayOwnerModal/V2ProjectRiskNotice.tsx
  src/components/v2/V2Project/V2ConfirmPayOwnerModal/index.tsx
  src/components/v2/V2Project/V2PayButton.tsx
  src/components/v2/V2Project/index.tsx
  src/constants/v2/currency.ts
  src/contexts/v2/projectContext.ts
  src/hooks/v1/transactor/PayProjectTx.ts
  src/hooks/v2/contractReader/ETHPaymentTerminalBalance.ts
  src/hooks/v2/contractReader/ProjectTerminals.ts
  src/hooks/v2/contractReader/ProjectToken.ts
  src/hooks/v2/transactor/PayV2ProjectTx.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/models/v2/contracts.ts
Labels: Juicebox V2

#637 New manage tokens modal
  src/components/shared/RichButton.tsx
  src/components/v1/V1Create/index.tsx
  src/components/v1/V1Project/Rewards/ManageTokensModal.tsx
  src/components/v1/V1Project/Rewards/index.tsx
  src/components/v1/V1Project/modals/ParticipantsModal.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: bugish

#689 Fix resources submenu links
  src/components/Navbar/constants.ts
Labels: bug

#695 DIsplay project id in V2 project header
  src/components/v1/V1Project/modals/V1ConfirmPayOwnerModal/index.tsx
  src/components/v2/V2Project/V2ConfirmPayOwnerModal/index.tsx
  src/components/v2/V2Project/index.tsx
  src/components/v2/V2ProjectHeaderActions.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: V2

#697 Add Sentry for exception monitoring
  .example.env
  package.json
  src/hooks/Transactor.ts
  src/hooks/v1/contractReader/ContractReader.ts
  src/hooks/v2/contractReader/V2ContractReader.ts
  src/index.tsx
  src/lib/sentry.ts
  yarn.lock
Labels: housekeeping

#699 [docs] update documentation with the graph subgraph setup steps
  README.md
Labels: documentation

#708 [chore] fix typo in react query provider
  src/index.tsx
Labels: housekeeping

#654 V2 Reconfig - Project details
  src/components/shared/forms/ProjectDetailsForm.tsx
  src/components/v1/V1Project/modals/EditProjectModal.tsx
  src/components/v2/V2Create/models.ts
  src/components/v2/V2Project/V2ProjectReconfigureModal/V2ReconfigureModalTrigger.tsx
  src/components/v2/V2Project/V2ProjectReconfigureModal/drawers/V2ReconfigureProjectDetailsDrawer.tsx
  src/components/v2/V2Project/V2ProjectReconfigureModal/index.tsx
  src/components/v2/V2Project/index.tsx
  src/components/v2/V2ProjectHeaderActions.tsx
  src/hooks/v2/contractReader/HasPermission.ts
  src/hooks/v2/contractReader/OwnerOfProject.ts
  src/hooks/v2/transactor/EditV2ProjectDetailsTx.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: V2

#702 Improve currency context typing
  src/components/Landing/Payments.tsx
  src/components/Navbar/Balance.tsx
  src/components/Navbar/EthPrice.tsx
  src/components/shared/CurrencySymbol.tsx
  src/components/shared/ETHAmount.tsx
  src/components/shared/ETHToUSD.tsx
  src/components/shared/PayoutModsList.tsx
  src/components/shared/ProjectCard.tsx
  src/components/shared/formItems/ProjectPayoutMods.tsx
  src/components/shared/forms/BudgetForm.tsx
  src/components/shared/inputs/Pay/PayInputGroup.tsx
  src/components/shared/inputs/Pay/PayInputSubText.tsx
  src/components/v1/FundingCycle/FundingCycleDetails.tsx
  src/components/v1/FundingCycle/Spending.tsx
  src/components/v1/FundingCycle/modals/WithdrawModal.tsx
  src/components/v1/V1Create/ConfirmDeployProject.tsx
  src/components/v1/V1Dashboard/index.tsx
  src/components/v1/V1Project/BalanceTimeline.tsx
  src/components/v1/V1Project/FundingCycles/FundingHistory.tsx
  src/components/v1/V1Project/Paid.tsx
  src/components/v1/V1Project/ProjectActivity/RedeemActivity.tsx
  src/components/v1/V1Project/ProjectActivity/TapEventElem.tsx
  src/components/v1/V1Project/V1PayButton.tsx
  src/components/v1/V1Project/modals/ParticipantsModal.tsx
  src/components/v1/V1Project/modals/ReconfigureFCModal.tsx
  src/components/v1/V1Project/modals/RedeemModal.tsx
  src/components/v2/V2Create/DeployProjectModal/PayoutSplitsList.tsx
  src/components/v2/V2Create/DeployProjectModal/index.tsx
  src/components/v2/V2Create/index.tsx
  src/components/v2/V2Project/V2PayButton.tsx
  src/constants/v1/currency.ts
  src/constants/v2/currency.ts
  src/contexts/currencyContext.ts
  src/hooks/WeiConverter.ts
  src/providers/v1/V1CurrencyProvider.tsx
  src/providers/v2/V2CurrencyProvider.tsx
  src/redux/slices/editingProject.ts
  src/utils/formatCurrency.ts
Labels: housekeeping

#714 Add "In Juicebox" number to V2 projects
  src/components/Landing/Payments.tsx
  src/components/Projects/TrendingProjectCard.tsx
  src/components/shared/Project/StatLine.tsx
  src/components/shared/ProjectCard.tsx
  src/components/shared/currency/ETHAmount.tsx
  src/components/shared/currency/ETHToUSD.tsx
  src/components/shared/currency/USDAmount.tsx
  src/components/v1/V1Project/Paid.tsx
  src/components/v1/V1Project/ProjectActivity/PaymentActivity.tsx
  src/components/v2/V2Dashboard/index.tsx
  src/components/v2/V2Project/TreasuryStats.tsx
  src/components/v2/V2Project/index.tsx
  src/contexts/v2/projectContext.ts
  src/hooks/v2/contractReader/DistributionLimitCurrency.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: V2

#718 Fix funding target input field in create flow
  src/components/shared/formItems/ProjectTarget.tsx
  src/components/shared/formItems/formHelpers.tsx
  src/components/shared/inputs/BudgetTargetInput.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/utils/math.ts
Labels: bug

#719 Abstract progress bar into own component
  src/components/shared/Project/FundingProgressBar.tsx
  src/components/v1/V1Project/Paid.tsx
Labels: housekeeping

#720 Style Fix: misaligned project handle on edit payout modal
  src/components/shared/formItems/ProjectPayoutMods.tsx
Labels: bug

#725 Fix minting in manage tokens modal
  src/components/v1/V1Project/Rewards/ManageTokensModal.tsx
  src/components/v1/V1Project/Rewards/index.tsx
  src/components/v1/V1Project/modals/DownloadPaymentsModal.tsx
Labels: bug

#722 No explicit any
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/Projects/ProjectsFilterAndSort.tsx
  src/components/shared/ProjectCard.tsx
  src/components/shared/formItems/ProjectBondingCurveRate.tsx
  src/components/shared/formItems/ProjectPayoutMods.tsx
  src/components/shared/inputs/ImageUploader.tsx
  src/hooks/JuiceTheme.ts
  src/hooks/Transactor.ts
  src/hooks/v1/contractReader/ContractReader.ts
  src/hooks/v1/transactor/PrintTokensTx.ts
  src/hooks/v2/contractReader/V2ContractReader.ts
  src/utils/ipfs.ts
Labels: housekeeping

#723 Abstract funding cycle details card into own component
  src/components/shared/Project/FundingCycleDetailsCard.tsx
  src/components/shared/Project/FundingCycleSection.tsx
  src/components/v1/FundingCycle/CurrentFundingCycle.tsx
  src/components/v1/FundingCycle/FundingCyclePreview.tsx
  src/components/v1/V1Project/FundingCycles/index.tsx
  src/components/v1/V1Project/SectionHeader.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/styles/index.scss
  src/styles/utilities.scss
Labels: housekeeping

#726 V2 reconfig tokens tab
  src/components/v2/V2Create/tabs/FundingTab/FundingTabContent.tsx
  src/components/v2/V2Create/tabs/TokenTab/TokenTabContent.tsx
  src/components/v2/V2Dashboard/index.tsx
  src/components/v2/V2Project/V2ConfirmPayOwnerModal/index.tsx
  src/components/v2/V2Project/V2PayButton.tsx
  src/components/v2/V2Project/V2ProjectReconfigureModal/drawers/V2ReconfigureTokenDrawer.tsx
  src/components/v2/V2Project/V2ProjectReconfigureModal/index.tsx
  src/components/v2/V2Project/index.tsx
  src/contexts/v2/projectContext.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/models/v2/fundingCycle.ts
  src/redux/slices/editingV2Project.ts
Labels: V2

#732 Fix translations
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: bug, UI copy

#736 V2 splits + fixes to V2 units
  package.json
  src/components/Landing/Payments.tsx
  src/components/shared/Mod.tsx
  src/components/shared/ProjectTokenBalance.tsx
  src/components/shared/formItems/ProjectPayoutMods.tsx
  src/components/v1/V1Project/ProjectActivity/TapEventElem.tsx
  src/components/v1/shared/V1ProjectHandle.tsx
  src/components/v2/V2Create/DeployProjectModal/PayoutSplitsList.tsx
  src/components/v2/V2Create/DeployProjectModal/index.tsx
  src/components/v2/V2Create/tabs/FundingTab/FundingTabContent.tsx
  src/components/v2/V2Create/tabs/TokenTab/ReservedTokensFormItem.tsx
  src/components/v2/V2Dashboard/index.tsx
  src/components/v2/V2Project/V2FundingCycleSection/CurrentFundingCycle.tsx
  src/components/v2/V2Project/V2FundingCycleSection/FundingCycleDetails.tsx
  src/components/v2/V2Project/V2ProjectReconfigureModal/index.tsx
  src/components/v2/V2Project/index.tsx
  src/components/v2/shared/SplitItem.tsx
  src/components/v2/shared/SplitList.tsx
  src/contexts/v2/projectContext.ts
  src/hooks/v2/contractReader/HasPermission.ts
  src/hooks/v2/contractReader/ProjectDistributionLimit.ts
  src/hooks/v2/contractReader/ProjectMetadataContent.ts
  src/hooks/v2/contractReader/ProjectOwner.ts
  src/hooks/v2/contractReader/ProjectSplits.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/models/v2/contracts.ts
  src/utils/v2/math.ts
  src/utils/v2/splits.ts
  yarn.lock
Labels: bug, V2

#734 Add ability to reconfigure v2 project rules
  src/components/v2/V2Create/FormItemLabel.tsx
  src/components/v2/V2Create/tabs/FundingTab/FundingTabContent.tsx
  src/components/v2/V2Create/tabs/ProjectConfigurationFieldsContainer.tsx
  src/components/v2/V2Create/tabs/RulesTab/RulesTabContent.tsx
  src/components/v2/V2Create/tabs/TokenTab/TokenTabContent.tsx
  src/components/v2/V2Project/V2FundingCycleSection/FundingCycleDetails.tsx
  src/components/v2/V2Project/V2FundingCycleSection/index.tsx
  src/components/v2/V2Project/V2ProjectReconfigureModal/V2ReconfigureModalTrigger.tsx
  src/components/v2/V2Project/V2ProjectReconfigureModal/drawers/V2ReconfigureFundingDrawer.tsx
  src/components/v2/V2Project/V2ProjectReconfigureModal/index.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/utils/v2/currency.ts
Labels: V2

#739 Bump @jbx-protocol/contracts-v2 to v0.0.13
  package.json
  src/components/v2/V2Dashboard/index.tsx
  src/hooks/v2/contractReader/DistributionLimitCurrency.ts
  src/hooks/v2/contractReader/ProjectDistributionLimit.ts
  src/hooks/v2/transactor/DeployProjectTx.ts
  src/models/v2/contracts.ts
  yarn.lock
Labels: housekeeping, V2

#742 Contracts v2 bump 0.0.16
  package.json
  src/components/v2/V2Create/DeployProjectButton.tsx
  src/components/v2/V2Create/index.tsx
  src/components/v2/V2Dashboard/Dashboard.tsx
  src/components/v2/V2Dashboard/index.tsx
  src/components/v2/shared/V2MainnetWarning.tsx
  src/hooks/v2/transactor/PayV2ProjectTx.ts
  src/hooks/v2/transactor/ReconfigureV2FundingCycleTx.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/models/v2/fundingCycle.ts
  src/redux/slices/editingV2Project.ts
  src/utils/v2/__tests__/fundingCycle.test.ts
  src/utils/v2/fundingCycle.ts
  src/utils/v2/serializers.ts
  yarn.lock
Labels: V2
