Repository jbx-protocol/juice-interface, pull requests merged in 2022-06, with the labels that each got.

#1134 Fix distribute reserved button not wrapping on mobile
  src/components/v2/V2Project/V2FundingCycleSection/ReservedTokensSplitsCard.tsx
Labels: bug

#1170 Fix 404 initial load
  src/components/v2/V2Project/V2FundingCycleSection/ReservedTokensSplitsCard.tsx
  src/hooks/v2/contractReader/V2ContractReader.ts
Labels: bug, V2, severity::3

#1195 Fix iframe overlay in dev
  package.json
  yarn.lock
Labels: bug, housekeeping

#1203 [Critical] Fix reconfigure v2 project bug
  src/components/v2/V2Project/V2ProjectReconfigureModal/ReconfigurePreview.tsx
Labels: bug, severity::1

#1205 [Critical] Pay bug for very small amounts and issuance rate
  src/components/shared/inputs/Pay/PayInputSubText.tsx
Labels: bug, severity::1

#1208 [Critical] Apply rounding down decimal wei issuance rate to all cases
  src/components/shared/inputs/Pay/PayInputSubText.tsx
  src/utils/v2/math.ts
Labels: bug, severity::1

#1226 Fix bug where FC not loading in create
  src/components/v2/V2Project/V2FundingCycleSection/index.tsx
Labels: bug, severity::1

#1229 Fix bug where wagmi and canu can't be deleted as payouts from V1 JB
  src/components/v1/shared/ProjectPayMods/ProjectPayoutMods.tsx
Labels: bug, severity::1

#1234 Fix memo dark mode style
  src/components/shared/inputs/Pay/MemoFormItem.tsx
  src/components/v1/V1Project/modals/V1ConfirmPayOwnerModal.tsx
  src/components/v2/V2Project/V2PayButton/V2ConfirmPayModal/index.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/styles/antd-overrides/input.scss
Labels: bug, severity::3

#1238 Refactor tools drawer
  src/components/shared/ArchiveProject/index.tsx
  src/components/shared/MinimalCollapse.tsx
  src/components/shared/Project/ProjectHeader/SocialLinks.tsx
  src/components/shared/Project/ProjectHeader/index.tsx
  src/components/shared/Project/ProjectToolsDrawer/AddToProjectBalanceForm.tsx
  src/components/shared/Project/ProjectToolsDrawer/PayableAddressSection.tsx
  src/components/shared/Project/ProjectToolsDrawer/ProjectToolsDrawer.tsx
  src/components/shared/Project/ProjectToolsDrawer/TransferOwnershipForm.tsx
  src/components/shared/Project/ProjectToolsDrawer/TransferUnclaimedTokensForm.tsx
  src/components/shared/TransactorButton.tsx
  src/components/shared/modals/ProjectToolDrawerModal.tsx
  src/components/v1/V1Project/V1ProjectHeaderActions.tsx
  src/components/v1/V1Project/index.tsx
  src/components/v2/V2Project/V2ProjectHeaderActions.tsx
  src/components/v2/V2Project/index.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/styles/antd-overrides/layout.scss
Labels: enhancement, UX

#1235 Fix dark mode memo bugs
  src/components/shared/inputs/Pay/MemoFormItem.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/styles/antd-overrides/input.scss
Labels: bug, severity::3

#1256 Hide V2 Edit Payouts if no permission
  src/components/v2/V2Project/V2FundingCycleSection/PayoutSplitsCard.tsx
Labels: bug, severity::3

#1262 Collection of create form UX improvements
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  src/components/shared/Project/ProjectHeader/SocialLinks.tsx
  src/components/shared/Project/ProjectHeader/index.tsx
  src/components/shared/formItems/ProjectDiscord.tsx
  src/components/shared/formItems/ProjectLink.tsx
  src/components/shared/formItems/ProjectName.tsx
  src/components/shared/inputs/Pay/PayInputGroup.tsx
  src/components/v2/V2Create/ProjectConfigurationFieldsContainer.tsx
  src/components/v2/V2Create/index.tsx
  src/components/v2/V2Project/TreasuryStats/index.tsx
  src/components/v2/V2Project/V2FundingCycleSection/ReservedTokensSplitsCard.tsx
  src/components/v2/V2Project/V2FundingCycleSection/index.tsx
  src/hooks/v2/contractReader/HasPermission.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
  src/styles/antd-overrides/input.scss
Labels: enhancement, UX

#1239 Fix v2 page titles
  src/Router.tsx
  src/components/v1/V1Dashboard.tsx
  src/components/v2/V2Dashboard/index.tsx
  src/hooks/PageTitle.ts
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: bug, UX, severity::3

#1271 Archive some projects
  src/constants/v1/archivedProjects.ts
  src/constants/v1/projectIds.ts
  src/constants/v2/archivedProjects.ts
  src/constants/v2/projectIds.ts
Labels: V2, V1, archive request

#1268 Mint v1 validation
  src/components/shared/Callout.tsx
  src/components/shared/forms/ProjectDetailsForm.tsx
  src/components/v1/V1Project/modals/PrintPreminedModal.tsx
  src/components/v2/V2Create/FundingCycleExplainer.tsx
  src/components/v2/V2Create/forms/TokenForm/index.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: bug, V1, severity::2

#1285 Fix initial value bug on reserved split slider
  src/components/shared/modals/ReservedTokenReceiverModal.tsx
Labels: bug, severity::2

#1292 Fxi V2 add to balance
  src/components/shared/Project/ProjectToolsDrawer/AddToProjectBalanceForm.tsx
  src/hooks/v2/transactor/AddToBalanceTx.ts
Labels: bug, severity::1

#1296 Set tx metadata args to constant 0 value
  src/hooks/v2/transactor/AddToBalanceTx.ts
  src/hooks/v2/transactor/PayV2ProjectTx.ts
  src/hooks/v2/transactor/RedeemTokensTx.ts
Labels: bug, severity::3

#1293 Rework token form copy
  src/components/v2/shared/FundingCycleConfigurationDrawers/TokenDrawer.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: enhancement, UX

#1277 Home page rework
  src/components/Landing/HowItWorksSection.tsx
  src/components/Landing/SectionHeading.tsx
  src/components/Landing/StatsSection.tsx
  src/components/Landing/TopProjectsSection.tsx
  src/components/Landing/TrendingSection.tsx
  src/components/Landing/index.tsx
  src/components/Projects/TrendingProjects.tsx
  src/components/shared/Badge.tsx
  src/components/v2/V2Create/V2WarningBanner.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: enhancement
