Repository jbx-protocol/juice-interface, pull requests merged in 2022-02, with the labels that each got.

#463 Improve URL syncing on projects page
  src/components/Landing/index.tsx
  src/components/Projects/ProjectsTabs.tsx
  src/components/Projects/TrendingProjectCard.tsx
  src/components/Projects/TrendingProjects.tsx
  src/components/Projects/index.tsx
  src/components/shared/ProjectCard.tsx
  src/components/shared/ProjectHandle.tsx
Labels: enhancement

#476 Add missing translations from new redeem modal
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: bug

#459 Relocate component files
  src/components/Create/index.tsx
  src/components/Dashboard/index.tsx
  src/components/FundingCycle/CurrentFundingCycle.tsx
  src/components/FundingCycle/QueuedFundingCycle.tsx
  src/components/FundingCycle/ReservedTokens.tsx
  src/components/FundingCycle/Spending.tsx
  src/components/FundingCycle/modals/DistributeTokensModal.tsx
  src/components/FundingCycle/modals/WithdrawModal.tsx
  src/components/Landing/Payments.tsx
  src/components/Project/BalanceTimeline.tsx
  src/components/Project/FundingCycles/FundingHistory.tsx
  src/components/Project/FundingCycles/ReconfigureFundingModalTrigger.tsx
  src/components/Project/FundingCycles/index.tsx
  src/components/Project/Paid.tsx
  src/components/Project/Pay/PayInputSubText.tsx
  src/components/Project/Pay/index.tsx
  src/components/Project/ProjectActivity/ActivityTabContent.tsx
  src/components/Project/ProjectActivity/PaymentActivity.tsx
  src/components/Project/ProjectActivity/RedeemActivity.tsx
  src/components/Project/ProjectActivity/ReservesActivity.tsx
  src/components/Project/ProjectActivity/ReservesEventElem.tsx
  src/components/Project/ProjectActivity/TapActivity.tsx
  src/components/Project/ProjectActivity/TapEventElem.tsx
  src/components/Project/ProjectActivity/index.tsx
  src/components/Project/ProjectActivity/styles.ts
  src/components/Project/ProjectHeader.tsx
  src/components/Project/Rewards/IssueTickets.tsx
  src/components/Project/Rewards/index.tsx
  src/components/Project/SectionHeader.tsx
  src/components/Project/index.tsx
  src/components/Project/modals/BalancesModal.tsx
  src/components/Project/modals/ConfirmPayOwnerModal/ProjectRiskNotice.tsx
  src/components/Project/modals/ConfirmPayOwnerModal/index.tsx
  src/components/Project/modals/ConfirmUnstakeTokensModal.tsx
  src/components/Project/modals/DownloadParticipantsModal.tsx
  src/components/Project/modals/EditProjectModal.tsx
  src/components/Project/modals/MigrateV1Pt1Modal.tsx
  src/components/Project/modals/ParticipantsModal.tsx
  src/components/Project/modals/PayWarningModal.tsx
  src/components/Project/modals/PrintPreminedModal.tsx
  src/components/Project/modals/ProjectToolDrawerModal.tsx
  src/components/Project/modals/ReconfigureFCModal.tsx
  src/components/Project/modals/RedeemModal.tsx
  src/components/Project/styles.ts
  src/components/modals/ConfirmStakeTokensModal.tsx
  src/components/shared/Paragraph.tsx
  src/components/shared/RichNote.tsx
  src/components/shared/formItems/ProjectTicketMods.tsx
  src/components/shared/forms/BudgetForm.tsx
  src/components/shared/forms/IncentivesForm.tsx
  src/components/shared/forms/PayModsForm.tsx
  src/components/shared/forms/RestrictedActionsForm.tsx
  src/components/shared/forms/RulesForm.tsx
  src/components/shared/forms/TicketingForm.tsx
  src/components/shared/modals/ReservedTokenReceiverModal.tsx
Labels: housekeeping

#479 Translations lint
  .github/workflows/lint.yml
  package.json
  scripts/lint-translations.sh
Labels: housekeeping

#550 consolidate ci runs into one workflow and add lint caching
  .github/workflows/ci-run.yml
  .github/workflows/lint.yml
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: housekeeping

#539 Remove newlines from translated strings
  .github/workflows/crowdin-download.yml
  .husky/pre-commit
  CONTRIBUTING.md
  src/components/FundingCycle/FundingCyclePreview.tsx
  src/components/Project/Rewards/IssueTickets.tsx
  src/components/Project/Rewards/index.tsx
  src/components/shared/modals/ReservedTokenReceiverModal.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: enhancement, housekeeping

#556 Append newline to generated translation files
  package.json
  scripts/extract-translations.sh
Labels: housekeeping

#571 Update eslint config
  .eslintrc.json
  src/components/shared/FormattedAddress.tsx
  src/components/shared/formItems/EthAddress.tsx
  src/components/shared/formItems/ProjectBondingCurveRate.tsx
  src/hooks/Transactor.ts
  src/hooks/v1/ContractLoader.ts
  src/hooks/v1/contractReader/ContractReader.ts
  src/locales/ru/messages.po
  src/utils/formatCurrency.ts
  src/utils/ipfs.ts
Labels: housekeeping

#570 Make project header version-agnostic
  src/components/shared/ProjectHeader/SocialLinks.tsx
  src/components/shared/ProjectHeader/index.tsx
  src/components/v1/V1Project/ProjectHeader.tsx
  src/components/v1/V1Project/V1ProjectHeaderActions.tsx
  src/components/v1/V1Project/index.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: housekeeping

#569 Namespace v1 currency code
  src/components/Landing/Payments.tsx
  src/components/Navbar/Balance.tsx
  src/components/Navbar/EthPrice.tsx
  src/components/shared/CurrencySymbol.tsx
  src/components/shared/ETHAmount.tsx
  src/components/shared/ETHToUSD.tsx
  src/components/shared/InputAccessoryButton.tsx
  src/components/shared/PayoutModsList.tsx
  src/components/shared/formItems/ProjectPayoutMods.tsx
  src/components/shared/formItems/ProjectTarget.tsx
  src/components/shared/forms/BudgetForm.tsx
  src/components/shared/forms/PayModsForm.tsx
  src/components/shared/inputs/BudgetTargetInput.tsx
  src/components/shared/inputs/FormattedNumberInput.tsx
  src/components/v1/FundingCycle/FundingCycleDetails.tsx
  src/components/v1/FundingCycle/FundingCyclePreview.tsx
  src/components/v1/FundingCycle/ReservedTokens.tsx
  src/components/v1/FundingCycle/Spending.tsx
  src/components/v1/FundingCycle/modals/DistributeTokensModal.tsx
  src/components/v1/FundingCycle/modals/WithdrawModal.tsx
  src/components/v1/V1Create/ConfirmDeployProject.tsx
  src/components/v1/V1Create/index.tsx
  src/components/v1/V1Dashboard/index.tsx
  src/components/v1/V1Project/BalanceTimeline.tsx
  src/components/v1/V1Project/FundingCycles/FundingHistory.tsx
  src/components/v1/V1Project/FundingCycles/index.tsx
  src/components/v1/V1Project/Paid.tsx
  src/components/v1/V1Project/Pay/PayInputSubText.tsx
  src/components/v1/V1Project/Pay/index.tsx
  src/components/v1/V1Project/ProjectActivity/RedeemActivity.tsx
  src/components/v1/V1Project/ProjectActivity/TapEventElem.tsx
  src/components/v1/V1Project/Rewards/index.tsx
  src/components/v1/V1Project/index.tsx
  src/components/v1/V1Project/modals/ConfirmPayOwnerModal/ProjectRiskNotice.tsx
  src/components/v1/V1Project/modals/ConfirmPayOwnerModal/index.tsx
  src/components/v1/V1Project/modals/PrintPreminedModal.tsx
  src/components/v1/V1Project/modals/ReconfigureFCModal.tsx
  src/components/v1/V1Project/modals/RedeemModal.tsx
  src/constants/currency.ts
  src/constants/fundingWarningText.ts
  src/constants/v1/currency.ts
  src/hooks/AppSelector.ts
  src/hooks/v1/V1ContractLoader.ts
  src/hooks/v1/contractReader/CurrentFundingCycleOfProject.ts
  src/hooks/v1/contractReader/RedeemRate.ts
  src/hooks/v1/transactor/DeployProjectTx.ts
  src/hooks/v1/transactor/PrintTokensTx.ts
  src/hooks/v1/transactor/TapProjectTx.ts
  src/models/currency-option.ts
  src/models/v1/currencyOption.ts
  src/providers/v1/UserProvider.tsx
  src/redux/slices/editingProject.ts
  src/utils/formatCurrency.ts
  src/utils/math.ts
  src/utils/v1/currency.ts
  src/utils/v1/deepEqFundingCycles.ts
  src/utils/v1/fundingCycle.ts
  src/utils/v1/serializers.ts
Labels: housekeeping

#592 Use project's terminal in AddToBalance
  src/hooks/v1/transactor/AddToBalanceTx.ts
Labels: bug

#588 Add ability to config custom pinata gateway
  .example.env
  README.md
  src/constants/ipfs.ts
  src/utils/ipfs.ts
Labels: housekeeping

#590 Add scroll to top button
  src/components/shared/ScrollToTopButton.tsx
  src/components/v1/V1Dashboard/index.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: bugish, housekeeping

#610 Remove v1-specific copy from ProjectDetailsForm
  src/components/shared/forms/ProjectDetailsForm.tsx
  src/components/v1/V1Create/ProjectForm.tsx
  src/components/v1/V1Create/index.tsx
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: housekeeping
