Repository jbx-protocol/juice-interface, pull requests merged in 2022-08, with the labels that each got.

#1623 Move hamburger to right-hand-side on mobile
  src/components/Navbar/Mobile/MobileCollapse.tsx
Labels: ux:general

#1492 add disabled prop to v1 payment button
  src/components/inputs/FormattedNumberInput.tsx
  src/components/v1/V1Project/V1PayButton.tsx
Labels: blocked

#1663 Fix reserved rate `extra` on v2 edit modal
  src/components/v2/V2Project/V2FundingCycleSection/modals/EditTokenAllocationModal.tsx
Labels: type:bug, priority:2

#1649 [1/2] Remove string origins from translation files
  .linguirc.json
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/locales/fr/messages.po
  src/locales/pt/messages.po
  src/locales/ru/messages.po
  src/locales/tr/messages.po
  src/locales/zh/messages.po
Labels: type:maintenance

#1651 Minor pay memo fix
  src/hooks/ProcessedRichNote/ProcessedRichNote.ts
Labels: type:bug

#1650 [2/2] Translations overhaul
  .github/workflows/ci-run.yml
  .github/workflows/crowdin-download.yml
  .github/workflows/crowdin-upload.yml
  .gitignore
  package.json
  scripts/extract-translations-template.sh
  scripts/extract-translations.sh
  scripts/lint-translations-template.sh
  scripts/lint-translations.sh
  src/components/PayWarningModal.tsx
  src/locales/en/.gitkeep
  src/locales/messages.pot
Labels: type:maintenance

#1691 CSV upload for V2 payouts
  src/components/SplitCsvUpload/SplitCsvUpload.tsx
  src/components/v1/shared/PayoutModsList.tsx
  src/components/v2/V2Project/V2FundingCycleSection/modals/EditPayoutsModal.tsx
  src/locales/messages.pot
  src/utils/file.ts
Labels: type:enhancement, V2

#1713 Fix v2 weight reconfiguration
  src/components/v2/V2Project/V2ProjectReconfigureModal/hooks/reconfigureFundingCycle.ts
Labels: type:bug, priority:1

#1756 remove unneeded react imports
  src/components/Navbar/Mobile/ThemePickerMobile.tsx
  src/components/Navbar/ThemePicker.tsx
  src/components/icons/Sticker.tsx
  src/components/v1/V1Project/FundingCycles/ReconfigureFundingModalTrigger.tsx
  src/components/v1/V1Project/modals/ReconfigureFCModal.tsx
  src/components/v2/V2Project/V2FundingCycleSection/modals/EditPayoutsModal.tsx
  src/components/veNft/VeNftContent.tsx
  src/components/veNft/VeNftSummaryStatsSection.tsx
  src/components/veNft/formControls/AllowPublicExtensionInput.tsx
  src/components/veNft/formControls/VeNftTokenSelectInput.tsx
  src/pages/home/QAs.tsx
  src/pages/projects/HoldingsProjects.tsx
  src/pages/projects/index.page.tsx
Labels: type:maintenance

#1765 Fix tools drawer on mobile
  src/components/EtherscanLink.tsx
  src/components/FormattedAddress.tsx
  src/components/Project/ProjectToolsDrawer/PayableAddressSection.tsx
  src/components/v2/V2Project/ProjectPayersModal.tsx
  src/components/v2/V2Project/V2ProjectToolsDrawer/V2ProjectToolsDrawer.tsx
  src/utils/formatAddress.ts
Labels: type:bug, priority:2

#1780 Deleting payouts to Juicebox projects bug
  src/components/v2/shared/DistributionSplitsSection/index.tsx
Labels: type:bug, priority:1

#1835 Show upcoming fc tab with no duration, if reconfig
  src/components/v2/V2Project/V2FundingCycleSection/UpcomingFundingCycle.tsx
  src/components/v2/V2Project/V2FundingCycleSection/index.tsx
  src/hooks/v2/contractReader/ProjectUpcomingFundingCycle.ts
Labels: type:bug, priority:1

#1859 Fix upcoming FC logic
  src/components/v2/V2Project/V2ProjectReconfigureModal/ReconfigurePreview.tsx
  src/hooks/v2/contractReader/ProjectUpcomingFundingCycle.ts
  src/pages/create/tabs/ReviewDeployTab/FundingSummarySection.tsx
Labels: type:bug, priority:1

#1874 Some font optimisations
  src/components/common/Head/Head.tsx
  src/components/v2/V2Project/V2PayButton/V2ConfirmPayModal/index.tsx
  src/pages/index.page.tsx
  src/styles/web3-onboard-overrides/onboard/font.scss
  src/styles/web3-onboard-overrides/onboard/index.scss
Labels: performance
